DROP TABLE if exists Users;
DROP TABLE if exists Routines;


CREATE TABLE Users (
    USER_ID INTEGER PRIMARY KEY,
    FNAME TEXT NOT NULL,
    LNAME TEXT NOT NULL,
    EMAIL TEXT,
    PASSWORD TEXT 
);

CREATE TABLE Routines (
    ROUTINE_ID INTEGER PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    ROUTINE_NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID)
);